import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

import "@/app/globals.css";
import { auth } from "@/lib/auth";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();

	return (
		<html lang="en">
			<body className="antialiased">
				<SessionProvider session={session}>{children}</SessionProvider>
			</body>
		</html>
	);
}
